[package]
name = "histogram_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
csv = "1.2.2"
plotters = "0.3.5"
plotters-backend = "0.3"

